Create CODE_OF_CONDUCT.md
commudle/commudle-ng pull request #100
Opened 2021-01-02 14:10 UTC by tharunc

CODE_OF_CONDUCT.md has been created.

2021-01-02 16:15 UTC, arpansac commented
Hey I went through it, just 2 things, it
- It needs to mention that this code of conduct is for the developers contributing to Commudle
- It should mention the links to the privacy policy and T&C which are present on the official website
- It's link should be mentioned in the readme

2021-01-02 16:16 UTC, arpansac requested changes
Hey I went through it, just 2 things, it

It needs to mention that this code of conduct is for the developers contributing to Commudle
It should mention the links to the privacy policy and T&C which are present on the official website
It's link should be mentioned in the readme

2021-01-02 17:10 UTC, tharunc commented
Sure, but can you please mention the Line for the formatting to be done.

2021-01-03 04:28 UTC, arpansac reviewed
> Sure, but can you please mention the Line for the formatting to be done.

Sure, added 2 comments, for the 3rd point please put it just below the contribution guidelines link in the Readme

2021-01-03 04:28 UTC, arpansac commented on CODE_OF_CONDUCT.md
> +# Contributor Covenant Code of Conduct
For Commudle

2021-01-03 04:28 UTC, arpansac commented on CODE_OF_CONDUCT.md
> +
Add a section for T&C, Privacy Policy

2021-01-05 03:31 UTC, arpansac commented
Cool, will review and merge by tomorrow

2021-01-06 10:17 UTC, merged

2021-01-18 09:22 UTC, tharunc commented
Kindly add LEVEL tag for this merge.