refactor: attended members
commudle/commudle-ng pull request #1030
Opened 2023-07-14 15:51 UTC by Prerna290

## Type
- ( ) Fix
- (X) Refactor
- ( ) Style
- ( ) Docs
- ( ) Feat
- ( ) Hotfix

## Screenshots

## Bundle Size

2023-07-19 18:02 UTC, ArshdeepGrover requested changes

2023-07-19 18:02 UTC, ArshdeepGrover commented on apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-events/components/events-volunteer-list/events-volunteer-list.component.ts
> +  page_info: IPageInfo;
Let,s you camel case for variable name

2023-07-19 18:02 UTC, ArshdeepGrover commented on apps/commudle-admin/src/app/feature-modules/public-events/components/attended-members/attended-members-card/attended-members-card.component.ts
> +  CommonEvents() {
Let'S use more good name for functions?

2023-07-19 18:02 UTC, ArshdeepGrover commented on apps/commudle-admin/src/app/feature-modules/public-events/components/attended-members/attended-members.component.html
> -          </ng-container>
Why we are removing ng-container?

2023-07-19 18:02 UTC, ArshdeepGrover commented on apps/commudle-admin/src/app/feature-modules/public-events/components/attended-members/attended-members.component.ts
> -    this.subscriptions.push(
Why we are remving subscription?

2023-07-19 18:09 UTC, Prerna290 commented on apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-events/components/events-volunteer-list/events-volunteer-list.component.ts
> +  page_info: IPageInfo;
Done

2023-07-19 18:10 UTC, Prerna290 commented on apps/commudle-admin/src/app/feature-modules/public-events/components/attended-members/attended-members-card/attended-members-card.component.ts
> +  CommonEvents() {
Done

2023-07-20 05:47 UTC, ArshdeepGrover requested changes

2023-07-20 05:47 UTC, ArshdeepGrover commented on apps/commudle-admin/src/app/feature-modules/public-events/components/attended-members/attended-members-card/attended-members-card.component.ts
> +  CommonEventsAttended() {
let's rename this function name to better way

2023-07-20 05:47 UTC, ArshdeepGrover commented on apps/commudle-admin/src/app/feature-modules/public-events/components/attended-members/attended-members.component.ts
> +  page_info: IPageInfo;
let's rename this to camel case!

2023-07-20 05:47 UTC, ArshdeepGrover commented on apps/commudle-admin/src/app/feature-modules/public-events/components/attended-members/attended-members.component.ts
> +      .getAttendedMembers(this.page, this.count, this.event.id, this.query, this.employer, this.employee)
let's use subscriptions.push

2023-07-20 05:47 UTC, ArshdeepGrover commented on apps/commudle-admin/src/app/feature-modules/public-events/components/team/team.component.ts
>      this.eventsService.pGetEventVolunteers(this.event.id).subscribe((data) => {
let's use subscriptions.push

2023-07-20 05:47 UTC, ArshdeepGrover commented on apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-events/components/events-volunteer-list/events-volunteer-list.component.ts
> +    this.eventsService.pGetEventVolunteers(this.event.id).subscribe((data) => {
let's use subscriptions.push

2023-07-20 10:52 UTC, ArshdeepGrover approved these changes

2023-07-21 03:06 UTC, merged