style: builds preview image
commudle/commudle-ng pull request #1072
Opened 2023-08-16 14:57 UTC by Prerna290

## Type
- ( ) Fix
- ( ) Refactor
- ( ) Style
- ( ) Docs
- (X) Feat
- ( ) Hotfix

## Screenshots

## Bundle Size

2023-08-17 07:13 UTC, arpansac requested changes

2023-08-17 07:13 UTC, arpansac commented on apps/commudle-admin/src/app/feature-modules/community-builds/components/community-build/community-build-details/community-build-details.component.html
> +        <button (click)="imageNav(-1)" nbButton shape="round" size="small" [disabled]="isSingleImage()">
Store is single image in variable

2023-08-18 06:04 UTC, ArshdeepGrover approved these changes

2023-08-18 07:05 UTC, arpansac approved these changes

2023-08-18 07:05 UTC, merged