style: public event page
commudle/commudle-ng pull request #1073
Opened 2023-08-18 08:44 UTC by Prerna290

## Type
- ( ) Fix
- ( ) Refactor
- (X) Style
- ( ) Docs
- ( ) Feat
- ( ) Hotfix

## Screenshots

## Bundle Size

2023-08-28 06:29 UTC, ArshdeepGrover requested changes

2023-08-28 06:29 UTC, ArshdeepGrover commented on apps/commudle-admin/src/app/feature-modules/public-events/components/event-description/event-description.component.scss
> +      }
can we do this without ng: deep?

2023-08-28 07:21 UTC, arpansac commented
@Prerna290 please change the character limit to 2500 on description before showing view more

2023-08-29 13:48 UTC, ArshdeepGrover approved these changes

2023-08-31 07:49 UTC, merged