feat: reading book
commudle/commudle-ng pull request #1176
Opened 2023-12-07 08:05 UTC by Prerna290

# PR Template

## Type

- ( ) Fix
- ( ) Refactor
- ( ) Style
- ( ) Docs
- (X) Feat
- ( ) Hotfix

## description

## Screenshots

## Bundle Size
7.04 MB

2023-12-07 08:48 UTC, ArshdeepGrover requested changes

2023-12-07 08:48 UTC, ArshdeepGrover commented on apps/commudle-admin/src/app/feature-modules/public-reading-book/public-reading-book.module.ts
> +import { SharedPipesModule } from '../../../../../shared-pipes/pipes.module';
let's change the path to absolute

2023-12-07 08:48 UTC, ArshdeepGrover commented on apps/commudle-admin/src/app/feature-modules/public-reading-book/components/reading-book-index/reading-book-index.component.html
> +        {{ chapterIndex.chapter_name }}
lets put this in anchor tag

2023-12-07 08:48 UTC, ArshdeepGrover commented on apps/commudle-admin/src/app/feature-modules/public-reading-book/components/reading-book-index/reading-book-index.component.html
> +      <h2 [ngClass]="params === chapterIndex.slug.current ? 'active' : 'title'">
remove ng class and put routerLinkActive

2023-12-07 11:56 UTC, ArshdeepGrover approved these changes

2023-12-08 08:03 UTC, ArshdeepGrover requested changes

2023-12-08 08:03 UTC, ArshdeepGrover commented on apps/shared-models/reading_book.model.ts
> +export interface IReadingBookModel {
name should be IReadingBook

2023-12-08 08:03 UTC, ArshdeepGrover commented on apps/commudle-admin/src/app/feature-modules/public-reading-book/components/reading-book/reading-book.component.ts
> +  ngOnDestroy() {
NgOnDestroy should be implement before using

2023-12-11 08:44 UTC, ArshdeepGrover approved these changes

2023-12-11 11:37 UTC, arpansac approved these changes

2023-12-11 11:38 UTC, merged