fix: book and search page bugs
commudle/commudle-ng pull request #1190
Opened 2023-12-27 10:27 UTC by Prerna290

# PR Template

## Type

- (X) Fix
- ( ) Refactor
- ( ) Style
- ( ) Docs
- ( ) Feat
- ( ) Hotfix

## description

## Screenshots

## Bundle Size

2023-12-27 11:22 UTC, ArshdeepGrover requested changes

2023-12-27 11:22 UTC, ArshdeepGrover commented on apps/commudle-admin/src/app/feature-modules/public-book-page/components/book-page/book-page.component.ts
> +  constructor(private footerService: FooterService, private seoService: SeoService) {}
please implement onDestroy

2023-12-27 11:22 UTC, ArshdeepGrover commented on apps/commudle-admin/src/app/app-shared-components/app-shared-components.module.ts
> +    SharedPipesModule,
let's remove If not required!

2023-12-28 07:22 UTC, arpansac approved these changes

2023-12-28 07:22 UTC, merged