refactor: personal chat interface
commudle/commudle-ng pull request #1384
Opened 2024-06-05 14:16 UTC by Prerna290

# PR Template

## Type

- ( ) Fix
- (X) Refactor
- ( ) Style
- ( ) Docs
- ( ) Feat
- ( ) Hotfix

## description

## Screenshots
<img width="364" alt="image" src="https://github.com/commudle/commudle-ng/assets/86765602/78d00568-1277-4b49-9659-9aaac74cede7">

## Bundle Size

2024-06-06 07:15 UTC, ArshdeepGrover approved these changes

2024-07-01 12:31 UTC, ArshdeepGrover requested changes

2024-07-01 12:31 UTC, ArshdeepGrover commented on apps/shared-components/messages/messages-list/message/message.component.scss
> +  }
let's replace this with tailwindCss

2024-07-01 12:31 UTC, ArshdeepGrover commented on apps/shared-components/votes-display/votes-display.component.ts
> +  @Output() votesCount: EventEmitter<number> = new EventEmitter<number>();
rename this to voteCountUpdate

2024-07-02 07:14 UTC, arpansac commented
Message to be displayed to other user:
You have been blocked.

2024-07-03 07:07 UTC, ArshdeepGrover approved these changes

2024-07-03 07:10 UTC, merged