style: public hackathon schema
commudle/commudle-ng pull request #1455
Opened 2024-07-22 07:15 UTC by Prerna290

# PR Template

## Type

- ( ) Fix
- ( ) Refactor
- (X) Style
- ( ) Docs
- ( ) Feat
- ( ) Hotfix

## description

## Screenshots
<img width="754" alt="image" src="https://github.com/user-attachments/assets/7ecc99bc-912a-4d0d-8ead-04ce0438dcd0">
<img width="742" alt="image" src="https://github.com/user-attachments/assets/4e45aad7-2921-4e16-8378-8811eca029c1">
<img width="729" alt="image" src="https://github.com/user-attachments/assets/8386b3df-102e-47a5-b9d7-ceb523a15623">

## Bundle Size

2024-07-22 10:45 UTC, ArshdeepGrover requested changes

2024-07-22 10:45 UTC, ArshdeepGrover commented on apps/commudle-admin/src/app/feature-modules/public-hackathon/components/public-hackathon-homepage/public-hackathon-homepage.component.ts
> +        },
what if the hackathon is not online?

2024-07-22 10:45 UTC, ArshdeepGrover commented on apps/commudle-admin/src/app/feature-modules/public-hackathon/components/public-hackathon-homepage/public-hackathon-homepage.component.ts
> +        eventAttendanceMode: 'https://schema.org/OnlineEventAttendanceMode',
let's confirm for both fields, and when hackathon is not online then attendance mode will change

2024-07-22 10:45 UTC, ArshdeepGrover commented on apps/commudle-admin/src/app/feature-modules/public-hackathon/components/public-hackathon-homepage/public-hackathon-homepage.component.ts
> +        image: this.hackathon.banner_image ? this.hackathon.banner_image : this.community.logo_path,
I think we have to pass only one image url instead of image versions array

2024-07-22 10:45 UTC, ArshdeepGrover commented on apps/commudle-admin/src/app/feature-modules/public-hackathon/components/public-hackathon-homepage/public-hackathon-homepage.component.ts
> +      });
Are we giving some offers for hackathon?

2024-07-23 07:05 UTC, arpansac approved these changes

2024-07-23 07:07 UTC, ArshdeepGrover approved these changes

2024-07-23 07:07 UTC, merged