Changed the border radius of search-bar to 8px
commudle/commudle-ng pull request #244
Opened 2021-05-28 15:53 UTC by kaushiksriram16

2021-05-29 16:02 UTC, Ashwin-op requested changes

2021-05-29 16:02 UTC, Ashwin-op commented on projects/commudle-admin/src/app/components/search-bar/search-bar.component.scss
> +        border-bottom-left-radius: 8px;
Please use variables defined in variables.scss

2021-05-29 16:02 UTC, Ashwin-op commented on projects/commudle-admin/src/app/components/search-bar/search-bar.component.scss
> +          border-bottom-right-radius: 8px;
Please use variables defined in variables.scss

2021-05-29 16:02 UTC, Ashwin-op commented on projects/commudle-admin/src/app/components/search-bar/search-bar.component.scss
> +    border-bottom-left-radius: 8px;
Please use variables defined in variables.scss

2021-05-29 16:02 UTC, Ashwin-op commented on projects/commudle-admin/src/app/components/search-bar/search-bar.component.scss
> +      border-bottom-right-radius: 8px;
Please use variables defined in variables.scss

2021-05-29 16:02 UTC, Ashwin-op commented on projects/commudle-admin/src/app/components/search-bar/search-bar.component.html
> +  <div class="d-flex search-container" #searchContainer>
Why is this #searchContainer needed?

2021-05-29 16:02 UTC, Ashwin-op commented on projects/commudle-admin/src/app/components/search-bar/search-bar.component.ts
> +import {Component, ElementRef, OnDestroy, OnInit, ViewChild} from '@angular/core';
Please remove unused imports

2021-05-29 16:02 UTC, Ashwin-op commented on projects/commudle-admin/src/app/feature-modules/users/components/public-profile/user-basic-details/basic-user-profile/basic-user-profile.component.ts
> +import { NbDialogRef, NbDialogService } from '@nebular/theme';
Please remove unused imports

2021-05-29 16:02 UTC, Ashwin-op commented on projects/commudle-admin/src/app/feature-modules/users/components/public-profile/user-basic-details/basic-user-profile/basic-user-profile.component.ts
>          this.toastLogService.successDialog('Updated!');
Let's comment this toaster notification

2021-05-29 16:16 UTC, kaushiksriram16 commented on projects/commudle-admin/src/app/components/search-bar/search-bar.component.html
> +  <div class="d-flex search-container" #searchContainer>
It was from the previous commit when I used ViewChild 😅

2021-05-30 03:12 UTC, Ashwin-op approved these changes

2021-05-31 14:02 UTC, merged

2021-05-31 14:11 UTC, arpansac commented
Good Job @kaushiksriram16!!

Thanks for the review @Ashwin-op :)