Fix cookie window issues
commudle/commudle-ng pull request #248
Opened 2021-06-01 07:39 UTC by kaushiksriram16

* Delayed appearance of cookie window using setTimeout
* Removed all the buttons of cookie window header
* Removed the disagree button on the cookie window

   ![cw](https://user-images.githubusercontent.com/47670020/120284834-4e76ce00-c2da-11eb-9ad7-47c9410e5598.JPG)

2021-06-01 07:56 UTC, arpansac commented
@kaushiksriram16 can you please fix the bug on line 63 in the bug tracker as well in this same PR

2021-06-01 08:37 UTC, kaushiksriram16 commented
> @kaushiksriram16 can you please fix the bug on line 63 in the bug tracker as well in this same PR

I made it to appear 2-3 seconds after the page loads but just now I realized that it is also mentioned that it should appear only if it's browser, So I have to work on that.

2021-06-14 01:22 UTC, Ashwin-op requested changes
Please resolve merge conflicts also

2021-06-14 01:22 UTC, Ashwin-op commented on projects/commudle-admin/src/app/app.component.scss
> +        display: none;
This is affecting the join community dialog box and follow expert dialog box in the home page, as much as possible, let's avoid the `:host` selector

2021-06-17 08:26 UTC, merged