Feature tagging
commudle/commudle-ng pull request #346
Opened 2021-09-01 13:32 UTC by The-Vector-007

2021-09-03 15:44 UTC, Ashwin-op requested changes

2021-09-03 15:44 UTC, Ashwin-op commented on projects/shared-modules/mention/components/entity-profile/entity-profile.component.html
> +      <strong>{{ entity.name | slice:0:25 }}</strong>
Let's use truncate text pipe

2021-09-03 15:44 UTC, Ashwin-op commented on projects/shared-modules/mention/components/entity-profile/entity-profile.component.html
> +      {{ entity.username | slice:0:25 }}
Let's use truncate text pipe

2021-09-03 15:44 UTC, Ashwin-op commented on projects/shared-modules/mention/components/entity-profile/entity-profile.component.scss
> +    &.online {
Are these styles being used in the corresponding HTML file? If not, let's remove it

2021-09-03 15:44 UTC, Ashwin-op commented on projects/shared-modules/mention/components/suggestion-box/suggestion-box.component.scss
> +  background-color: cornflowerblue;
Let's use variables for colors, if the color you need doesn't have a variable, then create one

2021-09-03 15:44 UTC, Ashwin-op commented on projects/shared-modules/mention/directives/mention-directive/mention.directive.spec.ts
> +  it('should create an instance', () => {
We don't need this file, let's delete it

2021-09-03 15:44 UTC, Ashwin-op commented on projects/shared-modules/mention/service/mention.service.spec.ts
> +
We don't need this file, let's delete it

2021-09-03 15:44 UTC, Ashwin-op commented on projects/shared-modules/mention/mention.module.ts
> +    SuggestionBoxComponent,
Why have we added these components to this property?

2021-09-05 09:53 UTC, The-Vector-007 commented on projects/shared-modules/mention/components/entity-profile/entity-profile.component.html
> +      <strong>{{ entity.name | slice:0:25 }}</strong>
done!

2021-09-06 07:08 UTC, merged