fix: added emoji mart lib to personal chats
commudle/commudle-ng pull request #482
Opened 2022-02-02 16:32 UTC by The-Vector-007

![Screenshot 2022-02-02 220156](https://user-images.githubusercontent.com/55025205/152195912-1c8aab05-435a-4e99-99f8-dca23e5a0e80.png)

2022-02-03 08:58 UTC, The-Vector-007 commented
![Screenshot 2022-02-03 142744](https://user-images.githubusercontent.com/55025205/152311264-ae5f9950-70f7-4537-a588-74114dafa9db.png)

2022-02-04 05:32 UTC, Ashwin-op commented
@The-Vector-007 Not sure if we need to refactor the input component as a whole, but the UI looks different from the ones in channels, labs, etc.

2022-02-08 12:46 UTC, The-Vector-007 commented
![Screenshot 2022-02-08 181523](https://user-images.githubusercontent.com/55025205/152989771-caae42ea-1a29-41f7-8034-dda85ac54050.png)

2022-03-08 02:38 UTC, Ashwin-op requested changes

2022-03-08 02:38 UTC, Ashwin-op commented on projects/shared-components/discussion-personal-chat/discussion-personal-chat.component.scss
> +@import './projects/commudle-admin/src/assets/styles/variables';
Do we need this import here?

2022-03-08 02:38 UTC, Ashwin-op commented on projects/shared-components/discussion-personal-chat/discussion-personal-chat.component.ts
> +      content: currentValue.concat(`${event.emoji.native}  `),
Let's remove the space in the content

2022-03-08 02:48 UTC, Ashwin-op commented
There's a console error, please check it out 
![image](https://user-images.githubusercontent.com/60032753/157156493-5af6d221-cc7b-47f6-9d96-17eee35ee4b2.png)

2022-03-09 01:28 UTC, Ashwin-op requested changes
Couple of more changes are given as a comment

2022-03-21 11:23 UTC, merged