fix: added spinner when loading latest or previous messages
commudle/commudle-ng pull request #484
Opened 2022-02-03 14:02 UTC by The-Vector-007

2022-02-04 05:25 UTC, Ashwin-op requested changes

2022-02-04 05:25 UTC, Ashwin-op commented on projects/commudle-admin/src/app/feature-modules/community-channels/components/discussion-community-channel/discussion-community-channel.component.ts
> +    console.log(this.loadingMessages);
Let's remove console.log

2022-02-04 05:25 UTC, Ashwin-op commented on projects/commudle-admin/src/app/feature-modules/community-channels/components/discussion-community-channel/discussion-community-channel.component.ts
> +      console.log(this.loadingMessages);
Let's remove console.log

2022-02-04 05:25 UTC, Ashwin-op commented on projects/commudle-admin/src/app/feature-modules/community-channels/components/discussion-community-channel/discussion-community-channel.component.ts
> +          console.log(this.loadingMessages);
Let's remove console.log

2022-02-07 15:31 UTC, The-Vector-007 commented on projects/commudle-admin/src/app/feature-modules/community-channels/components/discussion-community-channel/discussion-community-channel.component.ts
> +    console.log(this.loadingMessages);
removed

2022-02-07 15:31 UTC, The-Vector-007 commented on projects/commudle-admin/src/app/feature-modules/community-channels/components/discussion-community-channel/discussion-community-channel.component.ts
> +          console.log(this.loadingMessages);
removed

2022-02-07 15:31 UTC, The-Vector-007 commented on projects/commudle-admin/src/app/feature-modules/community-channels/components/discussion-community-channel/discussion-community-channel.component.ts
> +      console.log(this.loadingMessages);
removed

2022-02-14 01:03 UTC, merged