feat: cookie constent changes
commudle/commudle-ng pull request #577
Opened 2022-06-29 14:22 UTC by ArshdeepGrover

Cookie consent changes

![image](https://user-images.githubusercontent.com/26763175/176460074-2a7f65fb-69f7-48d8-959e-062810d10eac.png)

2022-07-01 05:30 UTC, arpansac requested changes

2022-07-01 05:30 UTC, arpansac commented on projects/commudle-admin/src/app/app.component.ts
>        this.cookieAccepted = true;
Why has settimeout been removed?

2022-07-01 05:30 UTC, arpansac commented on projects/shared-components/cookie-consent/cookie-consent.component.ts
> +    this.close.emit(true);
Not correct

2022-07-01 05:30 UTC, arpansac commented on projects/commudle-admin/src/app/app.component.html
> +<app-chats-container *ngIf="currentUser"></app-chats-container>
Let's get cookie accepted here also

2022-07-01 05:30 UTC, arpansac commented on projects/shared-components/cookie-consent/cookie-consent.component.ts
> +    }
This code can be optimized, already discussed

2022-07-01 05:30 UTC, arpansac commented on projects/shared-components/cookie-consent/cookie-consent.component.ts
>    }
comment this out

2022-07-01 05:30 UTC, arpansac commented on tailwind.config.js
> +    },
remove

2022-07-01 10:05 UTC, ArshdeepGrover commented on projects/commudle-admin/src/app/app.component.ts
>        this.cookieAccepted = true;
set back again!

2022-07-06 11:48 UTC, arpansac approved these changes

2022-07-06 11:48 UTC, merged