feat: add blog page
commudle/commudle-ng pull request #587
Opened 2022-07-09 13:38 UTC by ArshdeepGrover

A blog page is added as    /blogs

2022-07-13 02:20 UTC, arpansac requested changes
Lots of mistakes, please fix it ASAP
Good job understanding sanity

2022-07-13 02:20 UTC, arpansac commented on projects/commudle-admin/src/app/feature-modules/public-blogs/Models/blogs.model.ts
> +export interface Blog {
Correction needed:
- folder name 
- interface name 

Please don't repeat these mistakes

2022-07-13 02:20 UTC, arpansac commented on projects/commudle-admin/src/app/feature-modules/public-blogs/components/blog/blog.component.html
> +      "name": "{{blog.username}}"
Can we also have a link to the profile here?

2022-07-13 02:20 UTC, arpansac commented on projects/commudle-admin/src/app/feature-modules/public-blogs/Models/blogs.model.ts
> +  description: string;
What is the use of description field? We did not discuss it

2022-07-13 02:20 UTC, arpansac commented on projects/commudle-admin/src/app/feature-modules/public-blogs/components/blog/blog.component.html
> +    "description": " {{ blog.description }} "
Description field not discussed yet

2022-07-13 02:20 UTC, arpansac commented on projects/commudle-admin/src/app/feature-modules/public-blogs/components/blog/blog.component.html
> +      "name": "commudle",
C capital, I think we can remove this part of the schema, but let's discuss

2022-07-13 02:20 UTC, arpansac commented on projects/commudle-admin/src/app/feature-modules/public-blogs/components/blog/blog.component.ts
> +    const slug: string = this.activatedRoute.snapshot.params.name;
the param name should be blogId

2022-07-13 02:20 UTC, arpansac commented on projects/commudle-admin/src/app/feature-modules/public-blogs/components/blog/blog.component.ts
> +      designation: this.blog.designation,
Why are we getting designation from the blog? We discussed to get it from the API????

2022-07-13 02:20 UTC, arpansac commented on projects/commudle-admin/src/app/feature-modules/public-blogs/Models/blogs.model.ts
> +  designation: string;
Why?

2022-07-13 02:20 UTC, arpansac commented on projects/commudle-admin/src/app/feature-modules/public-blogs/Models/blogs.model.ts
> +  name: string;
Why?

2022-07-13 02:20 UTC, arpansac commented on projects/commudle-admin/src/app/feature-modules/public-blogs/components/blog/blog.component.ts
> +
Where is meta??

2022-07-13 02:20 UTC, arpansac commented on projects/commudle-admin/src/app/feature-modules/public-blogs/components/blogs-list/blogs-list.component.html
> +/>
We specifically discussed that it will be done using the service?

2022-07-13 02:20 UTC, arpansac commented on projects/commudle-admin/src/app/feature-modules/public-blogs/components/blogs-list/blogs-list.component.html
> +                </p>
??????

2022-07-13 02:20 UTC, arpansac commented on projects/commudle-admin/src/app/feature-modules/public-blogs/components/blogs-list/blogs-list.component.ts
> +
Where is meta service?

2022-07-13 02:20 UTC, arpansac commented on projects/commudle-admin/src/app/feature-modules/public-blogs/public-blogs-routing.module.ts
> +    path: ':name',
Let's rename this to :id

2022-07-13 02:20 UTC, arpansac commented on projects/shared-services/cms.service.ts
> +      body
When we have a model defined, then why is this here?

2022-07-13 09:43 UTC, ArshdeepGrover commented on projects/commudle-admin/src/app/feature-modules/public-blogs/components/blog/blog.component.ts
> +
Done

2022-07-14 12:23 UTC, arpansac requested changes

2022-07-14 12:23 UTC, arpansac commented on projects/commudle-admin/src/app/feature-modules/public-blogs/components/blog/blog.component.ts
> +  meta_description: string;
Is this getting used? Why does the variable name have _?

2022-07-14 12:23 UTC, arpansac commented on projects/commudle-admin/src/app/feature-modules/public-blogs/components/blog/blog.component.ts
> +    console.log(slug);
???

2022-07-14 12:23 UTC, arpansac commented on projects/commudle-admin/src/app/feature-modules/public-blogs/components/blogs-list/blogs-list.component.ts
> +  constructor(private sanityService: CmsService, private seoService: SeoService, private meta: Meta) {}
Why are we importing meta if we are using seoService?

2022-07-14 12:23 UTC, arpansac commented on projects/commudle-admin/src/app/feature-modules/public-blogs/components/blogs-list/blogs-list.component.ts
> +  }
Why have we called the same function twice?

2022-07-15 12:12 UTC, merged

2022-07-18 03:49 UTC, Ashwin-op commented on projects/commudle-admin/src/app/feature-modules/public-blogs/components/blog/blog.component.scss
> +    @apply com-my-3 com-mb-5;
We can have margin-top and margin-bottom separately

2022-07-18 03:51 UTC, Ashwin-op commented on projects/commudle-admin/src/app/feature-modules/public-blogs/components/blog/blog.component.ts
> +import { IBlog } from '../../models/blogs.model';
absolute path

2022-07-19 05:55 UTC, Ashwin-op commented on projects/commudle-admin/src/app/feature-modules/public-blogs/components/blog/blog.component.ts
> +  subscriptions: Subscription[] = [];
unsubscribe these subscriptions

2022-07-19 05:55 UTC, Ashwin-op commented on projects/commudle-admin/src/app/feature-modules/public-blogs/components/blogs-list/blogs-list.component.ts
> +  constructor(private sanityService: CmsService, private seoService: SeoService) {}
same name for services

2022-07-19 05:55 UTC, Ashwin-op commented on projects/commudle-admin/src/app/feature-modules/public-blogs/components/blog/blog.component.ts
> +  richText: any;
can be string

2022-07-19 05:55 UTC, Ashwin-op commented on projects/commudle-admin/src/app/feature-modules/public-blogs/models/blogs.model.ts
> +  slug: [];
can be string

2022-07-19 05:55 UTC, Ashwin-op commented on projects/commudle-admin/src/app/feature-modules/public-blogs/models/blogs.model.ts
> +  headerImage: {};
can be SanityImageObject