Style-individual-lab-page
commudle/commudle-ng pull request #596
Opened 2022-07-25 01:52 UTC by ArshdeepGrover

2022-07-29 04:33 UTC, ArshdeepGrover commented
Text colour change from #536eff to #42AAFF

2022-07-29 04:34 UTC, ArshdeepGrover commented
![image](https://user-images.githubusercontent.com/26763175/181683459-8a2b9bd1-a91a-45d4-b148-498e3d21be47.png)

2022-09-19 14:14 UTC, ArshdeepGrover commented
![image](https://user-images.githubusercontent.com/26763175/191038351-46e898f0-3181-45f9-9200-da5ee01aa523.png)

2022-09-21 13:48 UTC, arpansac requested changes

2022-09-21 13:48 UTC, arpansac commented on .gitignore
> +.vscode/
fix

2022-09-21 13:48 UTC, arpansac commented on projects/commudle-admin/src/app/feature-modules/labs/components/lab/lab-step/lab-step.component.html
> +      <img [src]="src" alt="" class="image" />
add the name of the lab - step in this alt

2022-09-22 07:20 UTC, ArshdeepGrover commented on projects/commudle-admin/src/app/feature-modules/labs/components/lab/lab-step/lab-step.component.html
> +      <img [src]="src" [alt]="step.name" class="image" />
discuss alt name

2022-09-22 07:21 UTC, ArshdeepGrover commented on projects/commudle-admin/src/app/feature-modules/labs/components/lab/lab.component.html
> +      <img [src]="src" [alt]="lab.name" class="Image" />
check

2022-09-22 08:22 UTC, merged