fix: add chat, qna
commudle/commudle-ng pull request #625
Opened 2022-08-18 05:59 UTC by ArshdeepGrover

2022-09-07 11:46 UTC, arpansac commented
QnA not working, please fix

2022-09-14 15:57 UTC, arpansac requested changes

2022-09-14 15:57 UTC, arpansac commented on projects/commudle-admin/src/app/feature-modules/public-events/components/session-page/session-page-video/session-page-video.component.html
> +        (currentUser && ['commudle', 'youtube', 'other'].includes(embeddedVideoStream.source) && interactionWindows)
fix this

2022-09-14 15:57 UTC, arpansac commented on projects/commudle-admin/src/app/feature-modules/public-events/components/session-page/session-page-video/session-page-video.component.html
> +        (currentUser && ['commudle', 'youtube', 'other'].includes(embeddedVideoStream.source) && interactionWindows)
fix condition

2022-09-14 15:57 UTC, arpansac commented on projects/commudle-admin/src/app/feature-modules/public-events/components/session-page/session-page-video/session-page-video.component.ts
> +    if (this.embeddedVideoStream === undefined || ['commudle', 'youtube'].includes(this.embeddedVideoStream.source)) {
Fix this, use iframe and check undefined condition, use !

2022-09-15 04:20 UTC, ArshdeepGrover commented on projects/commudle-admin/src/app/feature-modules/public-events/components/session-page/session-page-video/session-page-video.component.html
> +  "
check full screen condition

2022-09-15 07:14 UTC, arpansac approved these changes

2022-09-15 07:14 UTC, merged