feat: add notification section under community
commudle/commudle-ng pull request #640
Opened 2022-08-27 06:12 UTC by ArshdeepGrover

2022-09-01 06:41 UTC, ArshdeepGrover commented
![image](https://user-images.githubusercontent.com/26763175/187848602-5b650afa-f630-4415-b030-c19f2e215462.png)


![image](https://user-images.githubusercontent.com/26763175/187848655-6175d688-7dbf-475b-bfc9-904463bf584c.png)

2022-09-02 13:14 UTC, arpansac requested changes

2022-09-02 13:14 UTC, arpansac commented on projects/commudle-admin/src/app/components/sidebar-menu/sidebar-menu.component.ts
> +      this.communitiesService.getRoleCommunities(role).subscribe((data: ICommunities) => {});
no function needed inside the subscribe method

2022-09-02 13:14 UTC, arpansac commented on projects/commudle-admin/src/app/feature-modules/community-control-panel/community-control-panel-routing.module.ts
> +        path: 'notification',
notifications

2022-09-02 13:14 UTC, arpansac commented on projects/commudle-admin/src/app/feature-modules/community-control-panel/components/community-control-panel/community-control-panel.component.ts
> +      title: 'Notification',
notifications

2022-09-02 13:14 UTC, arpansac commented on projects/commudle-admin/src/app/feature-modules/community-control-panel/components/community-control-panel/community-control-panel.component.ts
> +      route: `./notification`,
notifications

2022-09-02 13:14 UTC, arpansac commented on projects/commudle-admin/src/app/feature-modules/notifications/services/notification.service.ts
rename to notifications.service

2022-09-02 13:14 UTC, arpansac commented on projects/commudle-admin/src/app/feature-modules/public-community/components/home-community/home-community.component.ts
> +    }
Optimize this

2022-09-02 13:14 UTC, arpansac commented on projects/commudle-admin/src/app/feature-modules/public-community/public-community-routing.module.ts
> +        path: 'notification',
notifications

2022-09-02 13:35 UTC, merged