refactor: improve UI of new login page
commudle/commudle-ng pull request #791
Opened 2022-12-29 07:35 UTC by ArshdeepGrover

![Screenshot from 2022-12-29 12-11-20](https://user-images.githubusercontent.com/26763175/209918777-2e418380-a8bb-4681-a490-558794f5e9a3.png)
![Screenshot from 2022-12-29 12-11-48](https://user-images.githubusercontent.com/26763175/209918785-74e67e5a-6036-4270-a737-2e9e97343d60.png)
![Screenshot from 2022-12-29 12-12-01](https://user-images.githubusercontent.com/26763175/209918788-7d649e15-d056-4fb5-8c6f-50a8f5accf89.png)

2022-12-29 13:59 UTC, Ashwin-op requested changes

2022-12-29 13:59 UTC, Ashwin-op commented on apps/commudle-admin/src/app/components/login/login.component.scss
> +      @apply com-mt-8 com-mb-20 #{!important};
Let's avoid !important

2022-12-29 13:59 UTC, Ashwin-op commented on apps/commudle-admin/src/app/components/login/login.component.ts
> +    this.libAuthWatchService.currentUser$.subscribe((currentUser) => {
Add to subscriptions array

2022-12-29 14:00 UTC, Ashwin-op commented on apps/commudle-admin/src/app/components/login/login.component.ts
> +      ? window.location.origin + this.activatedRoute.snapshot.queryParams.redirect
Why was this needed?

2023-01-11 06:22 UTC, ArshdeepGrover commented
Need some major changes so closed and make new PR

2023-01-11 06:22 UTC, closed without merging