style: changes in job-list-page, job-form and user-details
commudle/commudle-ng pull request #814
Opened 2023-02-02 13:52 UTC by Prerna290

2023-02-02 15:16 UTC, Prerna290 commented
![job-edit-form](https://user-images.githubusercontent.com/86765602/216363572-7bbfad64-ca5d-4baa-99b3-41e6a0b72a7d.png)
![user-details](https://user-images.githubusercontent.com/86765602/216363981-2c887e04-4414-43f1-b9a1-fef1f6dd1a45.png)

![Job page-Load More Jobs](https://user-images.githubusercontent.com/86765602/216364018-c3d14ab8-68ee-4a88-96f9-d3b344ce2447.png)

2023-02-03 09:11 UTC, ArshdeepGrover approved these changes

2023-02-04 07:10 UTC, arpansac requested changes

2023-02-04 07:10 UTC, arpansac commented on apps/commudle-admin/src/app/feature-modules/users/components/public-profile/user-extra-details/user-job/user-job.component.ts
> +  }
Make central method or use some autoresize

2023-02-07 14:09 UTC, ArshdeepGrover approved these changes

2023-02-08 07:24 UTC, arpansac approved these changes

2023-02-08 07:24 UTC, merged