style: changes in error404 page
commudle/commudle-ng pull request #816
Opened 2023-02-03 18:19 UTC by Prerna290

![error404-page](https://user-images.githubusercontent.com/86765602/216677892-ff0b931e-9d2d-4994-b40e-31d5a968b394.png)
![community-page](https://user-images.githubusercontent.com/86765602/216677906-d1ed16b4-dcdb-4bbb-a017-5cd3e9a1333d.png)

2023-02-03 18:29 UTC, ArshdeepGrover requested changes

2023-02-03 18:29 UTC, ArshdeepGrover commented on apps/lib-error-handler/src/lib/components/error404-page/error404-page.component.html
> +        src="https://json.commudle.com/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcWNWIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--f0111f34be8851dba07ca43f8ec5bdcee98d455b/404.gif"
why there is an empty line?

2023-02-03 18:29 UTC, ArshdeepGrover commented on apps/lib-error-handler/src/lib/components/error404-page/error404-page.component.html
> +        alt=""
we have to put text in the alt 
@arpansac suggest some text

2023-02-08 07:12 UTC, arpansac approved these changes

2023-02-08 07:12 UTC, merged