refactor: closed icon on user profile
commudle/commudle-ng pull request #852
Opened 2023-02-18 07:01 UTC by Prerna290

2023-02-18 07:06 UTC, Prerna290 commented
<img width="1090" alt="image" src="https://user-images.githubusercontent.com/86765602/219846531-d71fa9ea-def8-4b03-ae31-0363f401953f.png">
<img width="319" alt="image" src="https://user-images.githubusercontent.com/86765602/219846654-06c3871a-8ccb-4381-acf5-514ccfdb9ee3.png">

2023-02-18 09:03 UTC, ArshdeepGrover requested changes

2023-02-18 09:03 UTC, ArshdeepGrover commented on apps/commudle-admin/src/app/feature-modules/users/components/public-profile/public-profile.component.html
> +                    }} com-text-[18px] com-leading-[24px]"
Try to use tailwind colours

2023-02-21 11:38 UTC, arpansac commented
++ Resume icon should be hidden if no resume or for other users' profile

2023-02-28 18:39 UTC, closed without merging