fix: event banner image
commudle/commudle-ng pull request #857
Opened 2023-02-21 06:20 UTC by Prerna290

2023-02-21 11:26 UTC, Prerna290 commented
<img width="1324" alt="image" src="https://user-images.githubusercontent.com/86765602/220332582-606a6d55-e483-429e-b52f-b4992937a56d.png">
<img width="626" alt="image" src="https://user-images.githubusercontent.com/86765602/220332761-55318d4d-d62b-46e4-9c4a-b4a579e1e641.png">

2023-02-21 11:59 UTC, arpansac requested changes

2023-02-21 11:59 UTC, arpansac commented on apps/commudle-admin/src/app/feature-modules/public-events/components/home-event/home-event.component.scss
> +        -webkit-filter: blur(8px);
use overflow hidden on parent to define clear edges

2023-02-22 06:51 UTC, Prerna290 commented
<img width="1389" alt="image" src="https://user-images.githubusercontent.com/86765602/220544695-66181bf0-4b35-4687-8c13-1565a8e57035.png">

2023-02-22 07:26 UTC, merged