Style registration popup
commudle/commudle-ng pull request #893
Opened 2023-03-27 11:10 UTC by Prerna290

## Type
- ( ) Fix
- ( ) Refactor
- ( ) Style
- ( ) Docs
- (X) Feat
- ( ) Hotfix

## Screenshots

## Bundle Size

2023-03-27 11:11 UTC, ArshdeepGrover requested changes

2023-03-27 11:11 UTC, ArshdeepGrover commented on apps/commudle-admin/src/app/feature-modules/events/components/event-dashboard/form-groups/form-groups.component.html
> +  <div class="newDataFormTemplate">
Use correct name pattern

2023-03-27 11:11 UTC, ArshdeepGrover commented on apps/commudle-admin/src/app/feature-modules/events/components/event-dashboard/form-groups/form-groups.component.scss
> +  width: calc(100% - 16px);
Use tailwind classes

2023-03-28 16:04 UTC, ArshdeepGrover approved these changes

2023-03-29 08:04 UTC, Prerna290 commented
<img width="515" alt="image" src="https://user-images.githubusercontent.com/86765602/228512757-d2ac3772-c5d4-4a00-9862-2e7d4caaf911.png">
<img width="1186" alt="image" src="https://user-images.githubusercontent.com/86765602/228512928-db5794b5-d3d0-4de5-87f9-d386a4bc0b79.png">

2023-03-29 10:57 UTC, ArshdeepGrover approved these changes

2023-03-29 13:26 UTC, arpansac approved these changes

2023-03-29 13:26 UTC, merged