refactor: validation in community form
commudle/commudle-ng pull request #916
Opened 2023-04-04 19:01 UTC by Prerna290

## Type
- ( ) Fix
- (X) Refactor
- ( ) Style
- ( ) Docs
- ( ) Feat
- ( ) Hotfix

## Screenshots
<img width="912" alt="image" src="https://user-images.githubusercontent.com/86765602/229893495-70abaf33-829b-47b6-b14c-296117be617f.png">
<img width="629" alt="image" src="https://user-images.githubusercontent.com/86765602/229893675-aa3e0cbb-0ec9-4f33-be5e-9c26610464d5.png">

## Bundle Size

2023-04-05 12:15 UTC, arpansac requested changes

2023-04-05 12:15 UTC, arpansac commented on apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-edit-details/community-edit-details.component.html
> +          <span *ngIf="communityForm.get('community').get('about').touched">
Fix this please

2023-04-05 12:15 UTC, arpansac commented on apps/shared-components/tag/tag.component.html
> +<span *ngIf="tags.length <= 0">
min 5 tags should be present.

2023-04-05 15:55 UTC, Prerna290 commented on apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-edit-details/community-edit-details.component.html
> +          <span *ngIf="communityForm.get('community').get('about').touched">
fixed

2023-04-05 15:55 UTC, Prerna290 commented on apps/shared-components/tag/tag.component.html
> +<span *ngIf="tags.length <= 0">
Done

2023-04-06 06:07 UTC, ArshdeepGrover approved these changes

2023-04-06 06:09 UTC, ArshdeepGrover approved these changes

2023-04-08 07:16 UTC, ArshdeepGrover approved these changes

2023-04-08 07:17 UTC, merged