feat: cookies
commudle/commudle-ng pull request #943
Opened 2023-04-25 12:48 UTC by Prerna290

## Type
- ( ) Fix
- ( ) Refactor
- ( ) Style
- ( ) Docs
- (X) Feat
- ( ) Hotfix

## Screenshots
<img width="1433" alt="image" src="https://user-images.githubusercontent.com/86765602/234280942-357fc4bd-09e6-43c9-bbd3-c512d8675037.png">

## Bundle Size
4.88 MB

2023-04-26 04:56 UTC, ArshdeepGrover requested changes

2023-04-26 04:56 UTC, ArshdeepGrover commented on apps/shared-components/cookie-consent/cookie-consent.component.ts
> +  allowMarketing = true;
is this needed?

2023-04-26 07:23 UTC, Prerna290 commented on apps/shared-components/cookie-consent/cookie-consent.component.ts
> +  allowMarketing = true;
removed

2023-04-26 11:57 UTC, ArshdeepGrover requested changes

2023-04-26 11:57 UTC, ArshdeepGrover commented on apps/commudle-admin/src/app/feature-modules/users/components/public-profile/user-basic-details/cookie-preferences/cookie-preferences.component.scss
> +  height: 620px;
try to use tailwindCss

2023-04-26 13:20 UTC, Prerna290 commented on apps/commudle-admin/src/app/feature-modules/users/components/public-profile/user-basic-details/cookie-preferences/cookie-preferences.component.scss
> +  height: 620px;
Done

2023-04-27 05:41 UTC, ArshdeepGrover approved these changes

2023-05-02 11:49 UTC, merged