refactor: student non profit community
commudle/commudle-ng pull request #945
Opened 2023-04-26 13:34 UTC by Prerna290

## Type
- ( ) Fix
- ( ) Refactor
- ( ) Style
- ( ) Docs
- (X) Feat
- ( ) Hotfix

## Screenshots

## Bundle Size

2023-04-27 05:44 UTC, ArshdeepGrover requested changes

2023-04-27 05:44 UTC, ArshdeepGrover commented on apps/commudle-admin/src/app/feature-modules/student-non-profit-support/student-non-profit-support-routing.module.ts
> +// /student-non-profit-community-support
please remove this, if not needed

2023-04-27 05:47 UTC, Prerna290 commented on apps/commudle-admin/src/app/feature-modules/student-non-profit-support/student-non-profit-support-routing.module.ts
> +// /student-non-profit-community-support
Done

2023-04-28 08:40 UTC, arpansac approved these changes

2023-04-28 08:40 UTC, merged