refactor: logout navbar
commudle/commudle-ng pull request #948
Opened 2023-04-28 06:12 UTC by Prerna290

## Type
- ( ) Fix
- (X) Refactor
- ( ) Style
- ( ) Docs
- ( ) Feat
- ( ) Hotfix

## Screenshots

## Bundle Size
4.89 MB

2023-04-28 06:50 UTC, ArshdeepGrover requested changes

2023-04-28 06:50 UTC, ArshdeepGrover commented on apps/commudle-admin/src/app/components/navbar-menu/navbar-menu.component.ts
> +  faEllipsisV = faEllipsisV;
Are we using this?

2023-04-28 06:52 UTC, ArshdeepGrover requested changes

2023-04-28 06:52 UTC, ArshdeepGrover commented on apps/commudle-admin/src/app/components/navbar-menu/navbar-menu.component.html
> +      <fa-icon [icon]="faInfo"></fa-icon>
fa-circle-info

for about we are using this please replace this

2023-05-02 05:22 UTC, arpansac commented
use filled icons @Prerna290 
Order of items

Logged out: 
1. About
2. Communities
3. Builds
4. Pricing
5. More [Labs, Jobs, Newsletters, Blogs, Documentation]

2023-05-16 10:04 UTC, ArshdeepGrover approved these changes

2023-06-03 09:46 UTC, merged