refactor: events listing page
commudle/commudle-ng pull request #976
Opened 2023-05-19 12:45 UTC by Prerna290

## Type
- ( ) Fix
- (X) Refactor
- ( ) Style
- ( ) Docs
- ( ) Feat
- ( ) Hotfix

## Screenshots

## Bundle Size

2023-05-25 09:35 UTC, ArshdeepGrover requested changes

2023-05-25 09:35 UTC, ArshdeepGrover commented on NX
Please remove this!

2023-05-25 09:35 UTC, ArshdeepGrover commented on apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-events/components/public-home-list-events-featured-communities-card/public-home-list-events-featured-communities-card.component.html
> +  <a [routerLink]="[]" target="_blank">
RouterLink was empty?

2023-05-25 09:35 UTC, ArshdeepGrover commented on apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-events/components/public-home-list-events-featured-communities-card/public-home-list-events-featured-communities-card.component.scss
> +      @apply com-rounded-none com-object-cover com-object-center com-align-middle com-mr-4;
We are using two lines here?

2023-05-25 09:35 UTC, ArshdeepGrover commented on apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-events/components/public-home-list-events-past-card/public-home-list-events-past-card.component.html
> +  <a [routerLink]="[]">
routerLink was empty?

2023-06-06 06:38 UTC, ArshdeepGrover requested changes

2023-06-06 06:38 UTC, ArshdeepGrover commented on NX
Let's remove this file

2023-06-06 06:38 UTC, ArshdeepGrover commented on apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-events/components/public-home-list-events-past/public-home-list-events-past.component.ts
> +  total;
Lets' define data type!

2023-06-06 06:38 UTC, ArshdeepGrover commented on apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-events/components/public-home-list-events-speakers/public-home-list-events-speakers.component.ts
> +  total;
Let's define data type

2023-06-06 06:38 UTC, ArshdeepGrover commented on apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-events/components/public-home-list-events-upcoming/public-home-list-events-upcoming/public-home-list-events-upcoming.component.ts
> +  total;
Let's define data type

2023-06-06 06:38 UTC, ArshdeepGrover commented on apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-events/services/public-home-list-events.service.ts
Are we using this service?

2023-06-06 06:38 UTC, ArshdeepGrover commented on apps/shared-modules/mini-user-profile/components/profile-cards/user-profile-card-large/user-profile-card-large.component.html
> +    <app-user-follow [username]="user.username" [isMobileWidthFull]="true" Fullclass="follow-btn"></app-user-follow>
Why are we using this?
what is Fullclass

2023-06-06 06:38 UTC, ArshdeepGrover commented on apps/shared-modules/mini-user-profile/components/user-follow/user-follow.component.scss
> +      @apply com-bg-red-500 com-w-full;
we are using the background colour red?

2023-06-06 06:38 UTC, ArshdeepGrover commented on tailwind.preset.js
> +        'Bright-Gray-Light': '#EAECF0',
we are renaming this?

2023-06-06 06:38 UTC, ArshdeepGrover commented on tailwind.preset.js
> -        AuroMetalSaurus: '#667085',
are we not using this further?

2023-06-06 06:38 UTC, ArshdeepGrover commented on apps/shared-models/sessions.model.ts
> +}
@arpansac is this a good way?
or we are using I Event

2023-06-06 06:38 UTC, ArshdeepGrover commented on apps/commudle-admin/src/app/app-shared-components/events-upcoming-card/events-upcoming-card.component.html
Let's rename this component name!

2023-06-06 06:38 UTC, ArshdeepGrover commented on apps/commudle-admin/src/app/app-shared-components/events-upcoming-card/events-upcoming-card.component.html
> +<div class="border"></div>
Let optimise this in good way with edge case?
1. what if there is only one card is shown?
2. Is this have to show border everywhere

2023-06-06 06:38 UTC, ArshdeepGrover commented on apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-events/services/public-home-list-events.service.spec.ts
Let's remove this file

2023-06-06 07:19 UTC, Prerna290 commented on apps/commudle-admin/src/app/app-shared-components/events-upcoming-card/events-upcoming-card.component.html
event-horizontal-card

2023-06-06 11:21 UTC, merged