style: buils-card
commudle/commudle-ng pull request #996
Opened 2023-06-09 18:47 UTC by Prerna290

## Type
- ( ) Fix
- ( ) Refactor
- (X) Style
- ( ) Docs
- ( ) Feat
- ( ) Hotfix

## Screenshots

## Bundle Size

2023-06-21 13:16 UTC, ArshdeepGrover requested changes

2023-06-21 13:16 UTC, ArshdeepGrover commented on apps/commudle-admin/src/app/feature-modules/community-builds/community-builds.module.ts
> +import { FeaturedProjectsCardComponent } from '../../app-shared-components/featured-projects-card/featured-projects-card.component';
let's give relative path while import

2023-06-21 13:16 UTC, ArshdeepGrover commented on apps/commudle-admin/src/app/feature-modules/community-builds/community-builds.module.ts
> +import { TopBuildersCardComponent } from '../../app-shared-components/top-builders-card/top-builders-card.component';
let's give relative path while import

2023-06-21 13:16 UTC, ArshdeepGrover commented on apps/commudle-admin/src/app/feature-modules/community-builds/community-builds.module.ts
> +import { SkeletonCardsComponent } from '../skeleton-screens/components/skeleton-cards/skeleton-cards.component';
let's give relative path while import

2023-06-21 13:16 UTC, ArshdeepGrover commented on apps/commudle-admin/src/app/feature-modules/community-builds/components/community-builds/community-build-card/community-build-card.component.scss
> +        // }
let's remove this if not needed!

2023-06-21 13:16 UTC, ArshdeepGrover commented on apps/shared-components/tag/tag.component.ts
> +    return this.tags.filter(Boolean).slice(0, 5);
we are fixing this to 5 why?

2023-06-21 13:16 UTC, ArshdeepGrover commented on apps/shared-components/tag/tag.component.ts
> +  @Input() customStyle: boolean = false;
Why are we using this?

2023-06-21 13:16 UTC, ArshdeepGrover commented on apps/shared-models/user.model.ts
> +  communities_count: number;
let's make this optional

2023-06-22 06:33 UTC, arpansac commented on apps/commudle-admin/src/app/app-shared-components/top-builders-card/top-builders-card.component.scss
> +            @apply md:com-text-sm com-text-xs com-font-normal com-mx-0 com-mb-1 com-text-Dark-Jungle-Green com-line-clamp-2;
Is dark jungle green actually green or grey?

2023-06-22 06:59 UTC, arpansac commented on apps/commudle-admin/src/app/feature-modules/community-builds/components/community-builds/builds-header/builds-header.component.ts
> +  constructor(private cmsService: CmsService) {}
Should we rename this service to sanity cms service?

2023-06-22 07:00 UTC, arpansac commented on apps/commudle-admin/src/app/feature-modules/community-builds/components/community-builds/builds-top-builders/builds-top-builders.component.html
> +          [text]="options[0]"
options is not a very good variable name

2023-06-22 07:11 UTC, merged